enum DriftAction {
  noAction,
  microSpeedUp,
  microSlowDown,
  hardSeek,
}

class SyncPayload {
  final String mediaType; // 'youtube' | 'direct_url' | 'bstation' | etc.
  final String mediaUrl;
  final String state; // 'playing' | 'paused' | 'buffering'
  final double positionSeconds;
  final int timestampMs;
  final double playbackSpeed;
  final String controllerId;
  final int seqId;
  final String? action; // 'play' | 'pause' | 'seek' | 'heartbeat' | 'media_change'
  final int? actionEpoch;
  final double? maxDurationSeconds;

  const SyncPayload({
    required this.mediaType,
    required this.mediaUrl,
    required this.state,
    required this.positionSeconds,
    required this.timestampMs,
    this.playbackSpeed = 1.0,
    required this.controllerId,
    this.seqId = 0,
    this.action,
    this.actionEpoch,
    this.maxDurationSeconds,
  });

  bool get isPlaying => state == 'playing';
  bool get isPaused => state == 'paused';
  bool get isBuffering => state == 'buffering';

  factory SyncPayload.fromJson(Map<String, dynamic> raw) {
    final json = (raw['payload'] is Map<String, dynamic>)
        ? raw['payload'] as Map<String, dynamic>
        : (raw['payload'] is Map)
            ? Map<String, dynamic>.from(raw['payload'] as Map)
            : raw;

    return SyncPayload(
      mediaType: json['media_type'] as String? ?? 'direct_url',
      mediaUrl: json['media_url'] as String? ?? '',
      state: json['state'] as String? ?? 'paused',
      positionSeconds: (json['position_seconds'] as num?)?.toDouble() ?? 0.0,
      timestampMs: (json['timestamp_ms'] as num?)?.toInt() ?? 0,
      playbackSpeed: (json['playback_speed'] as num?)?.toDouble() ?? 1.0,
      controllerId: json['controller_id'] as String? ?? '',
      seqId: (json['seq_id'] as num?)?.toInt() ?? 0,
      action: json['action'] as String?,
      actionEpoch: (json['action_epoch'] as num?)?.toInt(),
      maxDurationSeconds: (json['max_duration_seconds'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'media_type': mediaType,
      'media_url': mediaUrl,
      'state': state,
      'position_seconds': positionSeconds,
      'timestamp_ms': timestampMs,
      'playback_speed': playbackSpeed,
      'controller_id': controllerId,
      'seq_id': seqId,
      if (action != null) 'action': action,
      if (actionEpoch != null) 'action_epoch': actionEpoch,
      if (maxDurationSeconds != null) 'max_duration_seconds': maxDurationSeconds,
    };
  }

  /// Calculates estimated target position of host considering network latency and playback speed.
  /// If [durationLimit] is provided (or [maxDurationSeconds] was set), clamps within [0.0, duration].
  double calculateTargetPosition(int currentLocalTimestampMs, [double? durationLimit]) {
    if (state != 'playing') {
      return positionSeconds;
    }

    // Delta time in seconds since the packet was generated by host
    final double deltaSeconds = (currentLocalTimestampMs - timestampMs) / 1000.0;
    final double adjustedDelta = deltaSeconds > 0 ? deltaSeconds : 0;
    double target = positionSeconds + (adjustedDelta * playbackSpeed);

    final limit = durationLimit ?? maxDurationSeconds;
    if (limit != null && limit > 0) {
      target = target.clamp(0.0, limit);
    }
    return target;
  }

  /// Calculates drift (signed difference: target - local) between current client position and host target position
  double calculateSignedDrift(
      double currentLocalPositionSeconds, int currentLocalTimestampMs, [double? durationLimit]) {
    final double target = calculateTargetPosition(currentLocalTimestampMs, durationLimit);
    return target - currentLocalPositionSeconds;
  }

  /// Calculates drift (absolute difference) between current client position and host target position
  double calculateDrift(
      double currentLocalPositionSeconds, int currentLocalTimestampMs, [double? durationLimit]) {
    return calculateSignedDrift(currentLocalPositionSeconds, currentLocalTimestampMs, durationLimit).abs();
  }

  /// Determines appropriate drift correction action according to Section 3 of plan.md
  /// and enhanced state-aware rules (paused videos seek directly rather than micro-slewing).
  DriftAction evaluateCorrection(
      double currentLocalPositionSeconds, int currentLocalTimestampMs, [double? durationLimit]) {
    // 1. When video is paused or buffering, micro-speed cannot catch up.
    // Any significant desync (> 50ms) must be corrected by hard-seeking to the exact frame.
    if (state != 'playing') {
      final double drift = (positionSeconds - currentLocalPositionSeconds).abs();
      if (drift > 0.05) {
        return DriftAction.hardSeek;
      }
      return DriftAction.noAction;
    }

    // 2. Explicit seek actions must immediately trigger hard seek
    if (action == 'seek') {
      final double drift = (positionSeconds - currentLocalPositionSeconds).abs();
      if (drift > 0.05) {
        return DriftAction.hardSeek;
      }
      return DriftAction.noAction;
    }

    final double target = calculateTargetPosition(currentLocalTimestampMs, durationLimit);
    final double diff = target - currentLocalPositionSeconds;
    final double drift = diff.abs();

    // 3. Drift < 300ms (0.3s): Jitter tolerance -> No action
    if (drift < 0.3) {
      return DriftAction.noAction;
    }

    // 4. 300ms <= Drift < 2000ms (2.0s): Micro-Adjustment
    if (drift < 2.0) {
      if (diff > 0) {
        return DriftAction.microSpeedUp;
      } else {
        return DriftAction.microSlowDown;
      }
    }

    // 5. Drift >= 2000ms: Hard Seek
    return DriftAction.hardSeek;
  }

  SyncPayload copyWith({
    String? mediaType,
    String? mediaUrl,
    String? state,
    double? positionSeconds,
    int? timestampMs,
    double? playbackSpeed,
    String? controllerId,
    int? seqId,
    String? action,
    int? actionEpoch,
    double? maxDurationSeconds,
  }) {
    return SyncPayload(
      mediaType: mediaType ?? this.mediaType,
      mediaUrl: mediaUrl ?? this.mediaUrl,
      state: state ?? this.state,
      positionSeconds: positionSeconds ?? this.positionSeconds,
      timestampMs: timestampMs ?? this.timestampMs,
      playbackSpeed: playbackSpeed ?? this.playbackSpeed,
      controllerId: controllerId ?? this.controllerId,
      seqId: seqId ?? this.seqId,
      action: action ?? this.action,
      actionEpoch: actionEpoch ?? this.actionEpoch,
      maxDurationSeconds: maxDurationSeconds ?? this.maxDurationSeconds,
    );
  }
}
