enum DriftAction {
  noAction,
  microSpeedUp,
  microSlowDown,
  hardSeek,
}

class SyncPayload {
  final String mediaType; // 'youtube' | 'direct_url'
  final String mediaUrl;
  final String state; // 'playing' | 'paused' | 'buffering'
  final double positionSeconds;
  final int timestampMs;
  final double playbackSpeed;
  final String controllerId;

  const SyncPayload({
    required this.mediaType,
    required this.mediaUrl,
    required this.state,
    required this.positionSeconds,
    required this.timestampMs,
    this.playbackSpeed = 1.0,
    required this.controllerId,
  });

  bool get isPlaying => state == 'playing';
  bool get isPaused => state == 'paused';
  bool get isBuffering => state == 'buffering';

  factory SyncPayload.fromJson(Map<String, dynamic> raw) {
    final json = (raw['payload'] is Map<String, dynamic>)
        ? raw['payload'] as Map<String, dynamic>
        : (raw['payload'] is Map)
            ? Map<String, dynamic>.from(raw['payload'] as Map)
            : raw;

    return SyncPayload(
      mediaType: json['media_type'] as String? ?? 'direct_url',
      mediaUrl: json['media_url'] as String? ?? '',
      state: json['state'] as String? ?? 'paused',
      positionSeconds: (json['position_seconds'] as num?)?.toDouble() ?? 0.0,
      timestampMs: (json['timestamp_ms'] as num?)?.toInt() ?? 0,
      playbackSpeed: (json['playback_speed'] as num?)?.toDouble() ?? 1.0,
      controllerId: json['controller_id'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'media_type': mediaType,
      'media_url': mediaUrl,
      'state': state,
      'position_seconds': positionSeconds,
      'timestamp_ms': timestampMs,
      'playback_speed': playbackSpeed,
      'controller_id': controllerId,
    };
  }

  /// Calculates estimated target position of host considering network latency and playback speed
  double calculateTargetPosition(int currentLocalTimestampMs) {
    if (state != 'playing') {
      return positionSeconds;
    }

    // Delta time in seconds since the packet was generated by host
    final double deltaSeconds = (currentLocalTimestampMs - timestampMs) / 1000.0;
    final double adjustedDelta = deltaSeconds > 0 ? deltaSeconds : 0;
    return positionSeconds + (adjustedDelta * playbackSpeed);
  }

  /// Calculates drift (absolute difference) between current client position and host target position
  double calculateDrift(
      double currentLocalPositionSeconds, int currentLocalTimestampMs) {
    final double target = calculateTargetPosition(currentLocalTimestampMs);
    return (target - currentLocalPositionSeconds).abs();
  }

  /// Determines appropriate drift correction action according to Section 3 of plan.md
  DriftAction evaluateCorrection(
      double currentLocalPositionSeconds, int currentLocalTimestampMs) {
    final double target = calculateTargetPosition(currentLocalTimestampMs);
    final double diff = target - currentLocalPositionSeconds;
    final double drift = diff.abs();

    // 1. Drift < 300ms (0.3s): Jitter tolerance -> No action
    if (drift < 0.3) {
      return DriftAction.noAction;
    }

    // 2. 300ms <= Drift < 2000ms (2.0s): Micro-Adjustment
    if (drift < 2.0) {
      // If client is lagging behind host, speed up slightly
      if (diff > 0) {
        return DriftAction.microSpeedUp;
      } else {
        // If client is ahead of host, slow down slightly
        return DriftAction.microSlowDown;
      }
    }

    // 3. Drift >= 2000ms: Hard Seek
    return DriftAction.hardSeek;
  }

  SyncPayload copyWith({
    String? mediaType,
    String? mediaUrl,
    String? state,
    double? positionSeconds,
    int? timestampMs,
    double? playbackSpeed,
    String? controllerId,
  }) {
    return SyncPayload(
      mediaType: mediaType ?? this.mediaType,
      mediaUrl: mediaUrl ?? this.mediaUrl,
      state: state ?? this.state,
      positionSeconds: positionSeconds ?? this.positionSeconds,
      timestampMs: timestampMs ?? this.timestampMs,
      playbackSpeed: playbackSpeed ?? this.playbackSpeed,
      controllerId: controllerId ?? this.controllerId,
    );
  }
}
